### ISSUE TITLE
install: fatal: destination path already exists and is not an empty directory

### ISSUE THREAD

**Issue by tuxcanfly** [braydonf/gpk#11]
When `install` is run on package and it fails (most common reason being missing gpg keys), the next time it is run, it fails with this error. Would be nice to either

a) clean cache when install fails or

b) pre-emptively clear cache when installing new package or

c) prompt user to clean cache and re-download package

**Comment by braydonf** [comment]
If it's signed, there will be a different hash. So perhaps it just needs to give the same error, unable to verify.

**Comment by braydonf** [comment]
Actually, if there is a missing public key it would end up being the same. If the unverified path already exists, no need to fetch it again, just try verifying again.

**Comment by braydonf** [comment]
Closed in https://github.com/braydonf/gpk/commit/87578a30ad977ee9b80bc29e99ddf06012740bf7
