### ISSUE TITLE
'Error: Existing linked installation at...': maybe allow --force flag to replace?

### ISSUE THREAD

**Issue by pinheadmz** [braydonf/gpk#12]
I must have an older version installed. Had to `rm -rf` the old gpk from global node modules to install v1.0.0

**Comment by braydonf** [comment]
Was probably due to how the symlink was being created, relative vs absolute, so it was technically different.

**Comment by braydonf** [comment]
There could be a force option, also uninstalling it globally and adding it back is probably the best way, as there could be _additional_ bins linked that may not have be removed with a simple overwriting and replacing.
