### ISSUE TITLE
windows: global install path

### ISSUE THREAD

**Issue by tuxcanfly** [braydonf/gpk#6]
On Windows, `gpk install` fails:

```
$ ./bin/gpk install --global
gpk: [info] Installing 'gpk' at 'C:\Users\Javed\Work\gpk'.
gpk: [info] Building 'C:\Users\Javed\Work\gpk'.
gpk: [error] Error: ENOENT: no such file or directory, mkdir 'C:\Program Files\nodejs\lib\node_modules'
```
The libdir which is currently `C:/User/Program Files/nodejs` should be `C:/User/AppData/Roaming/npm` instead.

**Comment by braydonf** [comment]
So I think the nodejs paths are:
- `<global-nodejs-path>\node_modules\<module-name>` for libraries.
- `<global-nodejs-path>\<bin-name>` for binaries in the path.

The application data path (`AppData/Roaming`) is something npm specific, and you can install nodejs without npm.

**Comment by braydonf** [comment]
So `gpk` should be installed at `<global-nodejs-path>\gpk` and `<global-nodejs-path>\node_modules\gpk\`. And `gpk` would install modules by default at that same location. Otherwise using the `PREFIX` environment variable to specify an alternative location could work.

**Comment by tuxcanfly** [comment]
Yep. I think you can use the path returned by `npm config get prefix` or `npm prefix -g`: https://docs.npmjs.com/files/folders

**Comment by braydonf** [comment]
So `npm` uses a config file to specify the custom prefix. There is a file at `C:\Program Files\nodejs\node_modules\npm\npmrc` that has:
```
prefix=${APPDATA}\npm
```
This could alternatively be set using the PREFIX environment variable, or similar mechanism.

**Comment by tuxcanfly** [comment]
Edit: yes, I think `PREFIX` should work, even on Windows :+1: 

https://github.com/npm/cli/blob/latest/lib/config/defaults.js#L88

**Comment by braydonf** [comment]
And `gpk` reads at here https://github.com/braydonf/gpk/blob/master/lib/environment.js#L69-L83 as part of the `Environment`.

**Comment by tuxcanfly** [comment]
OK, maybe we could just document the usage for `PREFIX`.

Although without a prefix, the global install should write to `<global-nodejs-path>\node_modules\<module-name>` and `<global-nodejs-path>\<bin-name>`.

I think currently it writes to `<global-nodejs-path>/lib/node_modules` and `<global-nodejs-path>/bin/<bin-name>`. Otherwise we could just make a note to always use `PREFIX` and disallow global install to `C:/...` which would require admin privileges.

**Comment by braydonf** [comment]
Yeah, I think for now have a switch for `win32` to use `<global>\node_modules` instead of  `<global>\lib\node_modules` and `<global>\` instead of `<global>\bin`. And then the global prefix is optionally configured, for now PREFIX can be used (and possibly `GPK_PREFIX` to not conflict in namespace). Later `${APPDATA}\gpk` could be used for the prefix and added to the path.

**Comment by tuxcanfly** [comment]
Sounds good :+1:

**Comment by braydonf** [comment]
Also, permission issues are relevant to many OS environments, so worth documenting `PREFIX` (and/or `GPK_PREFIX`), especially for cases where Node.js is installed via an OS package manager such as `pacman`, `apt-get`, or compiled from source. These are usually installed at `/usr/lib` and `/usr/bin/` for unix-like installs that will require root for global installations as well. 

An alternative also being using `nvm` (or `n`) to install Node.js at `/home/<user>/.nvm/versions/node/<version>` as part of user's home directory.

**Comment by tuxcanfly** [comment]
I'd imagine inter-op between `npm` and `gpk` packages would continue to work, so maybe just using `PREFIX` would do. Using `GPK_PREFIX` could possibly isolate `gpk` packages.

**Comment by braydonf** [comment]
I've made this change at https://github.com/braydonf/gpk/commit/e46e14d5b023c243979a53f508f3543aff2d4e0f it also looks like a `gpk.cmd` file may be necessary.

**Comment by braydonf** [comment]
Added a `gpk.cmd` with https://github.com/braydonf/gpk/commit/27da6c225b7bd64c5f02b74e3f6c850118eec669 as the shebang in the executable is not honored.
