### ISSUE TITLE
windows: rebuild - spawn error UNKNOWN

### ISSUE THREAD

**Issue by tuxcanfly** [braydonf/gpk#7]
On Windows, `gpk rebuild` fails if any module requires `node-gyp`:

```
$ ../gpk/bin/gpk rebuild
gpk: [info] Building 'C:\Users\Javed\Work\bcoin'.
gpk: [info] Building 'C:\Users\Javed\Work\bcoin\node_modules\bcfg'.
gpk: [info] Building 'C:\Users\Javed\Work\bcoin\node_modules\bcrypto'.
gpk: [error] Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:547:9)
    at C:\Users\Javed\Work\gpk\lib\package.js:1451:21
    at new Promise (<anonymous>)
    at Package.rebuildModule (C:\Users\Javed\Work\gpk\lib\package.js:1450:12)
    at async Package.rebuild (C:\Users\Javed\Work\gpk\lib\package.js:1491:7)
    at async C:\Users\Javed\Work\gpk\bin\gpk:116:16
```

A probable fix is to prefix argument to `spawn` so that it executes: `node C:\\Users\\Javed\\Work\\gpk\\vendor\\node-gyp\\bin\\node-gyp.js` instead of the script directly.

The reason for this is on Windows, `spawn` does not honor shebang.

**Comment by braydonf** [comment]
Creating a file `gpk.cmd` along side `gpk` looks like ti will roughly translates the equivalent of the shebang.

```cmd
@ECHO OFF

"%~dp0\node.exe" "%~dp0\gpk" %*
```

This may work for node-gyp as well, or we can specify node as the executable in that case.

**Comment by braydonf** [comment]
I think this also a case for running tests with bmocha.

**Comment by braydonf** [comment]
Okay added in https://github.com/braydonf/gpk/commit/76c107d49f4397b8ac30980d534ab366f9a449e2

**Comment by braydonf** [comment]
Other shebang translation added in https://github.com/braydonf/gpk/commit/27da6c225b7bd64c5f02b74e3f6c850118eec669
